# Generated by Django 4.1.7 on 2023-05-19 11:57

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_ecom_item_type_ecom_product_sub_categories_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ecom_products',
            name='customer_id',
            field=models.ForeignKey(db_column='customer_id', default=django.utils.timezone.now, on_delete=django.db.models.deletion.PROTECT, related_name='customers_id', to='product.customer'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ecom_products',
            name='purchase_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
