# Generated by Django 4.1.7 on 2023-05-19 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_remove_ecom_products_customer_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='ecom_products',
            name='Agen_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
